import Vue from 'vue'

var c = {
  skyrocket: 'Skyrocket',
  skyrocket_description:
    "Ce forfait inclut toute les fonctionnalités de l'abonnement premium, en plus des extras",
  notif_new_order: 'Nouvelle commande',
  monday: 'Lundi',
  tuesday: 'Mardi',
  wednesday: 'Mercredi',
  thursday: 'Jeudi',
  friday: 'Vendredi',
  saturday: 'Samedi',
  sunday: 'Dimanche',
  MIN_PRICE: 'MIN_PRICE',
  MAX_PRICE: 'MAX_PRICE',
  CODE_INVALID: 'CODE_INVALID',
  CODE_NOT_ACTIVE: 'CODE_NOT_ACTIVE',
  CODE_EXPIRED: 'CODE_EXPIRED',
  CODE_MAX_USAGE: 'CODE_MAX_USAGE',
  CODE_MAX_PER_USER: 'CODE_MAX_PER_USER',
  CODE_ZERO_PRODUCT_SELECTED: 'CODE_ZERO_PRODUCT_SELECTED',
  CODE_INSUFFICIENT_QUANTITY: 'CODE_INSUFFICIENT_QUANTITY',
  percent_reduction: 'Pourcentage',
  fixed_amount_reduction: 'Montant fixe',
  bogo_discount: 'Bogo',
  product_offered: 'Produit offert',
  free_delivery: 'Livraison gratuite',
  subs_renewal: "Renouvellement d'abonnement",
  affiliate_deposit: 'Commission de parrainage',
  sms_pack: 'SMS package',
  cash: 'En espèces',
  d17: 'D17',
  check: 'Par chèques',
  minute_mandate: 'Mandat minute',
  bank_transfer: 'Versement Bancaire',
  credit_card: 'Carte Bancaire',
  maintenance: 'Entretien',
  repair: 'Réparation',
  fuel: 'Carburant',
  administrative: 'Administratifs',
  fine: 'Amendes',
  other: 'Autres',
  zone: 'Sortie de la zone',
  car_move: 'Début mouvement',
  over_speed: 'Excès de vitesse',
  shock: 'Choc',
  disconnected: 'Appareil GPS débranché',
  acceleration: 'Accélération forte',
  braking: 'Freinage fort',
  lateral_acceleration: 'Virage dangereux',
  reminder: 'Rappel',
  sms_insuffisant: 'Solde insuffisant (SMS non envoyé)',
  icon_zone: 'https://www.flaticon.com/svg/static/icons/svg/3720/3720281.svg',
  icon_new_order:
    'https://www.flaticon.com/svg/static/icons/svg/685/685388.svg',
  icon_lateral_acceleration:
    'https://www.flaticon.com/svg/static/icons/svg/3485/3485684.svg',
  icon_over_speed:
    'https://www.flaticon.com/svg/static/icons/svg/1606/1606598.svg',
  icon_shock: 'https://www.flaticon.com/svg/static/icons/svg/2471/2471290.svg',
  icon_disconnected:
    'https://www.flaticon.com/svg/static/icons/svg/969/969369.svg',
  icon_acceleration:
    'https://www.flaticon.com/svg/static/icons/svg/3696/3696431.svg',
  icon_braking:
    'https://www.flaticon.com/svg/static/icons/svg/2481/2481746.svg',
  icon_sms_insuffisant:
    'https://www.flaticon.com/svg/static/icons/svg/234/234129.svg',
  icon_reminder:
    'https://www.flaticon.com/svg/static/icons/svg/4285/4285654.svg',
  birth_date: 'Âge',
  permis_date: 'Années permis',
  reservation_date: 'Date de réservation',
  number_days: 'Nombre de jours',
  available: 'Disponible',
  draft: 'Brouillon',
  on_progress: 'En cours',
  on_hold: 'En attente',
  on_processing: 'Prise en charge',
  on_expedition: "En cours d'expédition",
  on_delivery: 'En cours de livraison',
  canceled: 'Annulée',
  succeeded: 'Terminée',
  failed: 'Echouée',
  activte: 'Activer',
  archived: 'Archivé',
  out_stock: 'En rupture de stock',
  color_available: '#2196F3',
  color_on_progress: '#EE82EE',
  color_on_hold: 'orange',
  color_on_processing: 'green',
  color_on_delivery: '#32CD32',
  color_canceled: 'grey',
  color_succeeded: 'green',
  color_failed: 'red',
  color_out_stock: 'red',
  color_archived: '#d3d3d3',
  color_activte: '#05a081',
  color_draft: '#d3d3d3',
  teleop: 'Téléopération',
  partner: 'Partenaire',
  particular: 'Particulier',
  pro: 'Professionnel',
  purchase: 'Achat',
  information: 'Information',
  sale: 'Vente',
  date_shortcuts: [
    { key: 'today', label: "Aujourd'hui", value: 'day' },
    { key: 'yesterday', label: 'Hier', value: '-day' },
    // { key: 'lastWeek', label: 'la semaine dernière', value: '-isoWeek' },
    { key: 'last7Days', label: '7 derniers jours', value: 7 },
    { key: 'last30Days', label: '30 derniers jours', value: 30 },
    { key: 'thisMonth', label: 'Ce mois', value: 'month' },
    { key: 'lastMonth', label: 'Le mois dernier ', value: '-month' },
    { key: 'thisYear', label: 'Cette année', value: 'year' },
    { key: 'lastYear', label: "L'année dernière", value: '-year' },
  ],
  VERY_GOOD: 'Très bonne affaire',
  GOOD: 'Bonne affaire',
  FAIR: 'Offre équitable',
  ABOVE_MARKET: 'Au-dessus du marché',
  FAR_ABOVE_MARKET: 'Hors marché',
  UNAVAILABLE: 'Analyse indisponible',
  COLOR_VERY_GOOD: '#5adc9d',
  COLOR_GOOD: '#5abbb8',
  COLOR_FAIR: '#559ee2',
  COLOR_ABOVE_MARKET: '#a86f8a',
  COLOR_FAR_ABOVE_MARKET: '#dc5a5a',
  COLOR_UNAVAILABLE: '#A0A0A0',
  ICON_VERY_GOOD: 'mdi-arrow-up-thick',
  ICON_GOOD: 'mdi-arrow-top-right-thick',
  ICON_FAIR: 'mdi-arrow-right-thick',
  ICON_ABOVE_MARKET: 'mdi-arrow-bottom-right-thick',
  ICON_FAR_ABOVE_MARKET: 'mdi-arrow-down-thick',
  ICON_UNAVAILABLE: 'mdi-progress-alert',
  trans: (key) => {
    if (c[key]) return c[key]
    else return key
  },
}

export default function ({}, inject) {
  inject('c', c)
}
